# Generated by Django 4.0.6 on 2022-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percent', models.IntegerField()),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
