# Generated by Django 4.0.6 on 2022-08-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts_compyuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percent', models.IntegerField()),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discounts_mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percent', models.IntegerField()),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discounts_appliance',
        ),
    ]
