# Generated by Django 4.0.6 on 2022-08-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_discounts_compyuter_discounts_mobiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='Gen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
