# Generated by Django 4.0.6 on 2022-08-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_computer_gen'),
    ]

    operations = [
        migrations.CreateModel(
            name='gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gen', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='Gen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfiles.gen'),
        ),
    ]
