# Generated by Django 4.0.6 on 2022-08-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_gen_alter_computer_gen'),
    ]

    operations = [
        migrations.CreateModel(
            name='core_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Core_i', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='Core_i',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfiles.core_i'),
        ),
    ]
