# Generated by Django 4.0.6 on 2022-08-16 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_appliance_image2_appliance_image3_appliance_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ram_mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ram', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ram',
            new_name='ram_compyuter',
        ),
        migrations.AddField(
            model_name='appliance',
            name='Product_I',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='Product_I',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Product_I',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfiles.ram_mobile'),
        ),
    ]
