# Generated by Django 4.0.6 on 2022-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0008_ram_mobile_rename_ram_ram_compyuter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram_compyuter',
            name='Ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ram_mobile',
            name='Ram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
