# Generated by Django 4.0.6 on 2022-08-16 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_alter_ram_compyuter_ram_alter_ram_mobile_ram'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appliance',
            new_name='appliances',
        ),
    ]
