# Generated by Django 4.0.6 on 2022-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_rename_appliance_appliances'),
    ]

    operations = [
        migrations.CreateModel(
            name='ffff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=25)),
            ],
        ),
    ]
