# Generated by Django 4.0.6 on 2022-08-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0011_ffff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliances',
            old_name='Product_I',
            new_name='Product_Information',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='Product_I',
            new_name='Product_Information',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='Product_I',
            new_name='Product_Information',
        ),
    ]
