# Generated by Django 4.0.6 on 2022-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0013_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
