# Generated by Django 4.0.6 on 2022-08-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0014_comment_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ffff',
        ),
    ]
