# Generated by Django 4.0.6 on 2022-08-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0016_rename_discounts_appliance_discounts_appliances_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appliances',
            new_name='appliance',
        ),
        migrations.RenameModel(
            old_name='Discounts_mobiles',
            new_name='Discounts_appliance',
        ),
        migrations.RenameModel(
            old_name='Discounts_appliances',
            new_name='Discounts_mobile',
        ),
        migrations.RenameModel(
            old_name='TopBrents',
            new_name='TopBrent',
        ),
        migrations.RenameModel(
            old_name='type_appliances',
            new_name='type_appliance',
        ),
    ]
