# Generated by Django 4.0.6 on 2022-08-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0021_remove_meetourteam_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField()),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
