# Generated by Django 4.0.6 on 2022-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0022_contact_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ram_compyuter',
            new_name='ram_computer',
        ),
        migrations.RenameModel(
            old_name='type_compyuter',
            new_name='type_computer',
        ),
        migrations.AlterField(
            model_name='appliance',
            name='Time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='Time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
