# Generated by Django 4.0.6 on 2022-08-31 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0023_rename_ram_compyuter_ram_computer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='Rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfiles.rating'),
        ),
        migrations.AddField(
            model_name='computer',
            name='Rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfiles.rating'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myfiles.rating'),
        ),
    ]
