# Generated by Django 4.0.6 on 2022-08-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0024_rating_appliance_rating_computer_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='Rating',
        ),
    ]
