# Generated by Django 4.0.6 on 2022-08-31 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0025_remove_appliance_rating_remove_computer_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MaxValueValidator(0)])),
            ],
        ),
        migrations.DeleteModel(
            name='rating',
        ),
    ]
