# Generated by Django 4.0.6 on 2022-09-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0026_ratings_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts_mobile',
            name='Review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
