# Generated by Django 4.0.6 on 2022-09-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0027_discounts_mobile_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounts_mobile',
            old_name='Review',
            new_name='comment',
        ),
    ]
