# Generated by Django 4.0.6 on 2022-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0028_rename_review_discounts_mobile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
