# Generated by Django 4.0.6 on 2022-09-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0029_appliance_rating_computer_rating_mobile_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ratings',
        ),
    ]
